### ISSUE TITLE
정보 가져올 때 한글 오류 발생

### ISSUE THREAD

**Issue by rudtjr1106** [PLUB2022/PLUB#14]
#13 성별, 이메일, 핸드폰 번호, 생년월일 까지 정확하게 가져오나 
한글 이름을 이상한 코드로 가져옵니다

조경석 => \uc870\uacbd\uc11d 
이런식으로... JSON에서 UTF-8로 저장이 안됐거나 가져올 때 문제가 있는 것 같은데 정확하게 찾는 방법을 몰라서 문제입니다..

**Comment by sectionr0** [comment]
UTF-8이 설정 안되서 생긴 문제인 것 같은데 테스트 해보겠습니다

**Comment by sectionr0** [comment]
Token정보를 통해 백에서 회원정보를 가져와서 해당 문제 해결됐습니다.

**Comment by sectionr0** [comment]
Token정보를 통해 백에서 회원정보를 가져와서 해당 문제 해결됐습니다.
